### ISSUE TITLE
PMC6368841 KEGG analysis

### ISSUE THREAD

**Issue by markziemann** [markziemann/enrichment_recipe#20]
https://github.com/markziemann/enrichment_recipe/blob/8a068145cb39f4b44828d3838f06a810e4d2ffb4/manuscript/manuscript.Rmd#L243

From the paper methods section, they stated that KEGG was done with clusterProfiler - should we reclassify this study?

**Comment by anusuiyaxbora** [comment]
Thank you for checking them again...
You are right, I rechecked with my lab notebook results and DAVID results seem to be consistent. I think this can be put into the 3 - good results.

- I know both Clusterprofiler and DAVID will give different results, but then how can we know which tool would be the best to use? We can maybe ask why clusterprofiler was preferred over DAVID?

**Comment by anusuiyaxbora** [comment]
Sorry, but I think we should shift this one to 3 (high) as if I just consider GO terms - they were similar and DAVID was just used for GO and not KEGG.

Yes, they have mixed the tools in the figures - so I can definitely add those lines.

For column B: A. Only GO Terms were the similar as the paper. The FDR values are inconsistent. However, the paper should have clearly mentioned the different tools under figure captions to bring more clarity of the terms obtained by respective tools like DAVID and ClusterProfiler. B. No

For column C: 3 (high). GO results from the original manuscript are somewhat similar to reproduced analysis in DAVID. The FDR values however are inconsistent. The list of genes as input into DAVID analysis is unclear. The paper should have mentioned that both up and down-regulated proteins were considered for DAVID analysis.

I have added some more points like why were two different tools used for GO and KEGG when both can be done in DAVID or Clusterprofiler...
