### ISSUE TITLE
PMC6381667

### ISSUE THREAD

**Issue by markziemann** [markziemann/enrichment_recipe#21]
methods section mentions IPA and DAVID, so there is confusion about which tool was used to generate each figure. Normally this information is included in the figure caption. Should be mention this in the table?

**Comment by anusuiyaxbora** [comment]
Yes, this is correct as well... They have mentioned DAVID is used for GO and KEGG but then GO Cluster results are given in a different format...

**Comment by anusuiyaxbora** [comment]
Sorry, but I think we should shift this one to 3 (high) as if I just consider GO terms - they were similar and DAVID was just used for GO and not KEGG. 

Yes, they have mixed the tools in the figures - so I can definitely add those lines. 

For column B: A. Only GO Terms were the similar as the paper. The FDR values are inconsistent. However, the paper should have clearly mentioned the different tools under figure captions to bring more clarity of the terms obtained by respective tools like DAVID and ClusterProfiler. B. No

For column C: 3 (high). GO results from the original manuscript are somewhat similar to reproduced analysis in DAVID. The FDR values however are inconsistent. The list of genes as input into DAVID analysis is unclear. The paper should have mentioned that both up and down-regulated proteins were considered for DAVID analysis.

**Comment by anusuiyaxbora** [comment]
I have added some more points like why were two different tools used for GO and KEGG when both can be done in DAVID or Clusterprofiler...
