### ISSUE TITLE
Adding about version numbers not being mentioned in the enrichment recipe manuscript?

### ISSUE THREAD

**Issue by anusuiyaxbora** [markziemann/enrichment_recipe#28]
Can we add something about version numbers not being mentioned in the enrichment recipe manuscript?

I have checked and found that only 5/20 papers have mentioned version numbers of DAVID. 4 of them have used v6.8, 1 has used v6.7.
15 articles didn't mention anything...

In this line: "The reproducibility analysis was performed using the respective methodologies stated in the methods sections of the 20 articles using the DAVID version specified in the articles (March-May 2022) [23]." 
I can add some more lines saying most of the articles did not state the version numbers but with article publishing timeline, there are chances of analysis being done using v6.7 or v6.8?

**Comment by markziemann** [comment]
Yes I have added the relevant details to the methods and results thanks!
> We attempted reproduction according to the methods described in the respective articles, with the limitation that we had to use DAVID v6.8 as v6.7 was no longer available.
