### ISSUE TITLE
Comments on enrichment letter

### ISSUE THREAD

**Issue by anusuiyaxbora** [markziemann/enrichment_recipe#32]
Some edits and comments in between the text (written in bold and italics):

1. They also require little training to use, which on one hand simplifies bioinformatics tasks, but on the other hand these tools can easily be misused and results misreported, which can lead to misleading conclusions [3,4]. **_Researchers also have bias towards tools that are commonly used and do not conduct their own due diligence on reliability of the results obtained by various web-based tools; there is negligence on verifying the results as it can be a time consuming process._** Last year we sought to test whether a small group of articles published in 2019 involving enrichment analysis with the DAVID tool [5] were reproducible using the authors’ own methods. We found **_only 4/20 enrichment studies_** had a high degree of reproduction, while 7/20 had severe discrepancies. After our pilot study completed, we were surprised to hear that **_the most commonly used version of DAVID till 2022_** for all of these studies (v6.8) would no longer be available from June 2022 onwards.

2. This is a prime example of “link decay,” a phenomenon where internet-based resources are lost over time, which has been raised as a significant and ongoing problem for bioinformatic reproducibility [6]. **_Can add About articles using enrichment tools just for the sake of it as it is evident by exclusion of DAVID results from conclusions of the paper? The problem of non-reproducibility is alarming as the presence of multiple articles using DAVID could be potentially used for pre-clinical studies._**  

3. **_Most of the articles are not concerned to mention versions used in their analysis... it is up to the interpretation of the reader. There should be guidelines by the journals to enforce minimum criteria to mention web-tools and softwares in the papers?_**  Researchers should keep in mind that institutional and funding mandates for data retention also apply to software and algorithms [7,8]. 

Will edit more if you like these points...

**Comment by markziemann** [comment]
Thanks so much Anusuiya! I have made some changes based on your comments and I hope you can include these in your thesis as well.

**Comment by anusuiyaxbora** [comment]
@markziemann 
Hi Mark, how about the alt title that you thought of before - "Time to abandon (most) web-based tools in genomics" 

Sounds crisp and might gather more interest...
